### ISSUE TITLE
install v2

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite_install_sh#1]
- ne serait-il pas intéressant de proposer un script d'install v2 ? En effet, on installe la V1 par défaut
- est-il pertinent de maintenir deux modes d'installation (script et plugin install) ?

**Comment by brunob** [comment]
>     * ne serait-il pas intéressant de proposer un script d'install v2 ? En effet, on installe la V1 par défaut

C'est déjà le cas, il ne manque plus que le merge de la v2 dans la branche master.

>     * est-il pertinent de maintenir deux modes d'installation (script et plugin install) ?

Oui, car tout le monde n'a pas un ssh sous la main, et le plugin d'install est bien utile sur un mutu ovh par exemple.

**Comment by brunob** [comment]
Pour info, je viens de passer la v2 dans le master.
