### ISSUE TITLE
installation de GIS 5.0

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite_install_sh#3]
la version installée par le script est GIS 5.0 et ça n'est pas compatible spip 4.0.
(je m'y remets...)

**Comment by brunob** [comment]
Tu es passé à côté de https://github.com/geodiversite/geodiversite_install_sh/commit/cf7a46582f359387879bb37dd75702c2c47a808a ?

**Comment by ubiquando** [comment]
En effet, je n'avais pas rechargé le nouveau script depuis 2 jours ;) merci !
