### ISSUE TITLE
instllation champs extra interface

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite_install_sh#4]
l'installation de champs extra interface nécessite  "API de verification" qui n'est pas installé

**Comment by brunob** [comment]
Ce plugin est dans plugins, donc optionnel, et donc SVP installera ses dépendances lors de son activation.

**Comment by ubiquando** [comment]
ben non, il ne l'a pas installé... je suis allé le chercher à la main. J'ai quand même l'impression que ma config est louche.

**Comment by brunob** [comment]
Et tu as bien activé le dépôt des plugins de la zone (celui proposé par défaut) ?

**Comment by ubiquando** [comment]
oui, enfin probablement pas tout de suite (uniquement quand j'ai voulu ajouter d'autres plugins), d'où le souci. J4ajoute cela dans l'article de doc en cours
