### ISSUE TITLE
erreur install : table spip_mailsubscriptions_optins manquante

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite_install_sh#5]
Au bout d'un court moment après installation, affichage d'un bug de squelette dans la partie ecrire .
Il semble que ce soit après un passage d'une tâche cron.
 
`<code>Erreur SQL 1146 Table 'edl7.spip_mailsubscriptions_optins' doesn't exist  SELECT * FROM spip_mailsubscriptions_optins LIMIT 1 | /home/edl7/public_html/geodiversite/ecrire/genie/maintenance.php | verifier_crash_tables(){ sql_select(); } | 73

1 Erreur(s) dans le squelette
1 	Erreur SQL 1146
Table 'edl7.spip_mailsubscriptions_optins' doesn't exist
SELECT * FROM spip_mailsubscriptions_optins LIMIT 1
	[/home/edl7/public_html/geodiversite/ecrire/genie/maintenance.php](https://v7.lespritdeslieux.fr/ecrire/?exec=auteurs&var_mode=debug&var_mode_affiche=squelette#L73)	[verifier_crash_tables(){ sql_select(); }](https://v7.lespritdeslieux.fr/ecrire/?exec=auteurs&var_mode=debugverifier_crash_tables(){sql_select();}&var_mode_affiche=boucle)	73
`</code>

**Comment by brunob** [comment]
Le problème concerne donc le plugin en question, pas geodiv...

PS : un passage par la page de maintenance et une réparation de la base de données corrigera ton bug.

**Comment by ubiquando** [comment]
merci, oui ça répare, mais comme j'ai tout installé depuis l'installeur geodiv je trouvais cela étrange; jamais eu ce problème avec ce plugin.
Par ailleurs j'ai un autre gros bug qui me chifonne, la table spip_articles_liens a disparu et ce n'est pas idéal... j'essaie d passer demain sur IRC

**Comment by brunob** [comment]
Cette table n'existe pas :)

**Comment by ubiquando** [comment]
ah oui en effet... hmm.
Le truc c'est que les media/articles ne s'affichent pas dans la partie ecrire dans les rubriques, ni dans les articles. Et je trouve cela étrange...
